#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:new_style1
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
import sys
from .ttypes import *
