<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
</head>
<body>
<p>Hi</p>

<p>
    This is an alert generated by system.
   </p>

<p>
    System noticed frequent email from email address {{$data["BlockedEmailAddress"]}}.
    </p>

<p>
System has generated Import Rule to avoid this problem.
    </p>

<p>Please check import rule entry.</p>

<p>{{$data["ImportRuleUrl"]}}</p>

</body>
</html>